### PR TITLE
UHM-4843: Improved data collection for Viral Load results

### PR DESCRIPTION
**Pull request by mogoodrich**

### CODE REVIEW

**Comment by mogoodrich** [comment]
@brandones can you take a look when you get a chance? The new form layout is up on Haiti HIV Test if you want to take a look at how it looks... I ran the migration locally and checked that it works at least for one "Detected" and one "Below Detectable Limit" use case...

**Review by mseaton — APPROVED** [review]
LGTM

**Review by brandones — APPROVED** [review]
Looks good, thanks Mark!

**Comment by mogoodrich** [comment]
Thanks guys, merging!

**Pull request merged**
